version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
      size: medium
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "src/ImpuestosBolivianos/ImpuestosBolivianos.csproj" }}-{{ checksum "src/ImpuestosBolivianos.Tests/ImpuestosBolivianos.Tests.csproj" }}
      - run:
          name: Restore packages
          command: cd ./src/ && dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/ImpuestosBolivianos/ImpuestosBolivianos.csproj" }}-{{ checksum "src/ImpuestosBolivianos.Tests/ImpuestosBolivianos.Tests.csproj" }}
      - run:
          name: Build
          command: cd ./src/ && dotnet build
      - run:
          name: Run tests
          command: cd ./src/ && dotnet test
